### ISSUE TITLE
Use with projected shapefiles

### ISSUE THREAD

**Issue by bmcbride** [calvinmetcalf/leaflet.shapefile#1]
What's the best way to deal with project shapefiles using the Leaflet plugin or isn't this currently supported? Thanks!

**Comment by patmccormick** [comment]
I just went through the process of figuring this out.  For me, the best approach was to use this plugin (leaflet.shapefile) and then access an ArcGIS server that happened to host what I was looking for.  I had tried loading the shapefile data as JSON into a JavaScript object and then loading that data to a map layer.

That worked, however, the page was hopelessly slow. Using this plugin and configuring it to fetch data from a server meant that the map only fetches the portion of data needed to populate the part of the map in the view port - not all of the data at once.

This plugin supports a variety of different map servers, which , in turn, provide a variety of different types of map data. I apologize if I'm being insultingly simple, but those explanations would have saved me a lot of time when I first started digging through online information. There's a lot to understand.

In the end - this plugin proved to provide the best and easiest solution in my particular case. I was mapping state counties and PLSS (Public Land Survey System) sections. Particular states can have upwards of 60,000 sections.  The settings for this plugin allow you to specify the levels of zoom within which each layer of data is visible.  I used that to show the counties when my users were zoomed out, then only display the smaller sections, once they reached a sufficient zoom level.

The performance is great because the map is never tyring to draw more than about 100 shapes at one time, rather than trying to draw them all as it would have, had I tried to load all that data as JSON, rather than fetch from a server.

Not sure of your particular situation, but for what you describe, this worked for me.

**Comment by calvinmetcalf** [comment]
so you have a couple choices on how you pass data to leaflet.shapefile, but they are get passed verbetim to shapefile-js, if you pass it a url that ends in .zip it looks for a zipfile otherwise it adds .shp and .dbf to the end and assumes thats all there is (you can also pass a zip as an array buffer).

currently if its dealing with a zipped shapefile it will look for a .prj file and if it finds that it will use that to project the data into wgs84.   the version in master uses a quick and dirty version of proj4js and only supports traverse mercator and labert conic conformal (which covers all of the us state plane except for the alaskan pan handle).  The version in the [require branch of shapefile-js](https://github.com/calvinmetcalf/shapefile-js/tree/require) uses a more complete version of proj4js and should handle _any_ proj file (as long as its in meters), I should have a that one cleaned up, built, and working for all units later today,

**Comment by calvinmetcalf** [comment]
ok the update is merged into master, so update your shp.js and (for now) make sure your shapefile is in a zipfile

**Comment by bmcbride** [comment]
Thanks!
