### ISSUE TITLE
Ordering different types of layers

### ISSUE THREAD

**Issue by ismail44** [calvinmetcalf/leaflet.shapefile#34]
I am trying to set an "order" on the layers on my map. I have WMS, WFS, KML, and now (thanks to your awesome plugin) SHP. I am trying to set the "z-index" on this layer, however, it says that the method does not exist.

Is it possible for me to be able to sort the viewing of a SHP layer? 

Basically, I want to be able to hide it behind say a KML at the same location.

Thanks.

**Comment by calvinmetcalf** [comment]
so behind the scenes all this plugin does is use shp.js to turn the shapefile into geojson and then load it as a geojson layer, so standard leaflet methods like bringToFront should be available depending on the leaflet version.   One thing to bear in mind is that since things are loaded async even if you put the shapefile layer on the map before the kml one the kml may load first and thus be underneath the shapefile.

More generally any app where you know the data before hand you should strongly consider NOT using this plugin and convert the shpfile into geojson ahead of time

**Comment by ismail44** [comment]
Thanks for the reply!

I've dug a bit deeper and I see that leaflet creates 2 divs... one for
tile-type layers (WMS, Base Layers, etc) and one for "overlays" (KML, SHP,
GeoJSON, etc). I can swap positioning between "same types", just not
between base and overlays (as one would expect).

And yeah... I don't know where someone may try to add layers from... I
offer them a box for a URL and they put it in (it's a semi-closed system).

**Comment by calvinmetcalf** [comment]
yes in leaflet 0.7 there are 2 different 'panes' one for overlays one for base layers
