### ISSUE TITLE
Support folder organization

### ISSUE THREAD

**Issue by DavidLibeau** [calvinmetcalf/leaflet.shapefile#54]
It seems that we can't put our ziped shapefile data and the shp.js file in any other place than the root folder. It could be cool to support folder organisation as : 
```
var shpfile = new L.Shapefile("path/to/shapefiles/data-shp.zip",{});
shpfile.addTo(map);
```

**Comment by calvinmetcalf** [comment]
`var shpfile = new L.Shapefile("path/to/shapefiles/data-shp.zip",{});` should work as long as `path/to/shapefiles/data-shp.zip` is something that the web browser can access.  Also I believe it does work with folders in the zip file, since it just streets the file paths as opaque strings it doesn't care if there are slashes in it, that though would be an issue for [shapefile-js](https://github.com/calvinmetcalf/shapefile-js) which handles that stuff.

**Comment by DavidLibeau** [comment]
Thanks for your reply.
In fact your are right. It seems that the issue comes only with relative path. You have to put absolute path, and without the first `/` (or it will output you CORS error because the script is looking for `//` path, a.k.a. the web).
Sorry !
